version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3305:${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
  # postgres-db:
  #   image: postgres
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: sawer
    # volumes:
    #   - db_data:/var/lib/postgresql/data
  sawer:
    build: .
    image: sawer
    container_name: sawer
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
    depends_on:
      - mysql-db

volumes:
  db_data: