version: '3.8'

services:
  mysql-db:
    image: mysql
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sawer
    volumes:
      - db_data:/var/lib/mysql

  sawer:
    build: .
    image: sawer
    container_name: sawer
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: sawer
      DB_PORT: 3306
      PORT: 9000

volumes:
  db_data: